#!/usr/bin/env python3
"""Turns ares' own account of its machines into the two things that must agree.

`gen-machines` builds every machine this core offers and prints what ares says
it is made of. This script turns that into:

  waterbox/machines.inc     the table the guest binds its inputs against
  waterbox/waterbox.config  the machines[] the frontend renders

Both are committed, and the gate regenerates them and diffs, because the wire
format of a controller is what a movie is written in: index 7 has to mean the
same button next year as it did when the movie was recorded. Deriving it from
the emulator rather than typing it twice is what makes that true.

    ./waterbox/gen-config.py [--check]

--check writes nothing and fails if what is committed is not what ares says.
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))


def port_prefix(name):
    """'Controller Port 2' -> 'P2'; anything else keeps a short readable form."""
    if name.startswith("Controller Port "):
        return "P" + name[len("Controller Port "):]
    if name == "Expansion Port":
        return "Exp"
    if name == "Extension Port":
        return "Ext"
    return name.replace(" Port", "")


def declare(machine):
    """The machine's buttons and axes, in the order that IS the wire format.

    Console inputs first, in ares' own order, then each port's devices. A name
    is qualified only as far as it needs to be: a handheld's buttons keep their
    own names, and a port's are prefixed by the port, and by the device too when
    the port offers more than one.
    """
    buttons, axes = [], []

    for i in machine["console"]:
        (axes if i["axis"] else buttons).append((i["name"], i["path"]))

    for port in machine["ports"]:
        prefix = port_prefix(port["name"])
        many = len(port["devices"]) > 1
        for device in port["devices"]:
            for i in device["inputs"]:
                name = f"{prefix} {device['name']} {i['name']}" if many else f"{prefix} {i['name']}"
                (axes if i["axis"] else buttons).append((name, i["path"]))

    return buttons, axes


def render_inc(machines):
    out = []
    out.append("/* GENERATED by waterbox/gen-config.py from waterbox/machines.json - do not edit.")
    out.append(" *")
    out.append(" * Which node each declared input binds to. The order is the wire format a")
    out.append(" * movie records, so it comes from ares itself (waterbox/gen-machines.cpp)")
    out.append(" * rather than from anybody's typing, and the gate checks it has not moved.")
    out.append(" */")
    out.append("")
    for m in machines:
        if not m["loads"]:
            continue
        buttons, axes = declare(m)
        ident = m["id"].replace("-", "_")
        out.append(f"static const machines::InputDecl kButtons_{ident}[] = {{")
        for name, path in buttons:
            out.append(f'\t{{"{name}", "{path}"}},')
        out.append("};")
        out.append(f"static const machines::InputDecl kAxes_{ident}[] = {{")
        for name, path in axes:
            out.append(f'\t{{"{name}", "{path}"}},')
        out.append("};")
        out.append("")
    out.append("static const machines::MachineInputs kMachineInputs[] = {")
    for m in machines:
        if not m["loads"]:
            continue
        buttons, axes = declare(m)
        ident = m["id"].replace("-", "_")
        b = f"kButtons_{ident}" if buttons else "nullptr"
        a = f"kAxes_{ident}" if axes else "nullptr"
        # what the first port takes when nobody says otherwise
        first = m["ports"][0]["devices"][0]["name"] if m["ports"] else None
        d = f'"{first}"' if first else "nullptr"
        out.append(f'\t{{"{m["id"]}", {b}, {len(buttons)}, {a}, {len(axes)}, {d}}},')
    out.append("};")
    out.append("")
    return "\n".join(out)


def render_machines(machines):
    """The machines[] block of waterbox.config."""
    result = []
    for m in machines:
        if not m["loads"]:
            continue
        buttons, axes = declare(m)
        entry = {
            "id": m["id"],
            "label": m["label"],
            "when": [m["id"].lower()],
            "input": {
                "name": f"{m['label']} Controller",
                "buttons": [n for n, _ in buttons],
            },
            "virtualWidth": m["virtualWidth"],
            "virtualHeight": m["virtualHeight"],
            "extensions": {"." + e: m["id"] for e in m["extensions"].split()},
        }
        if axes:
            entry["input"]["axes"] = [
                {"name": n, "min": -128, "max": 127, "neutral": 0} for n, _ in axes
            ]
        result.append(entry)
    return result


# What a button is bound to by default, by its own name. The frontend ships no
# bindings: a package that declares a controller says how it is played, and
# thirteen controllers is more than anybody should type twice.
#
# Only the FIRST port (or a handheld's own buttons) is bound, which is BizHawk's
# choice and the right one - a second pad is something you plug in deliberately,
# and the keys it would take are the ones player one already has.
DEFAULT_KEYS = {
    "Up": "Up, J1 POV1U, X1 DpadUp",
    "Down": "Down, J1 POV1D, X1 DpadDown",
    "Left": "Left, J1 POV1L, X1 DpadLeft",
    "Right": "Right, J1 POV1R, X1 DpadRight",
    "A": "X, J1 B1, X1 A",
    "B": "Z, J1 B3, X1 X",
    "C": "C, J1 B4, X1 Y",
    "X": "S, J1 B4, X1 Y",
    "Y": "A, J1 B2, X1 B",
    "Z": "LeftShift, J1 B7, X1 LeftTrigger",
    "Start": "Enter, J1 B10, X1 Start",
    "Select": "Space, J1 B9, X1 Back",
    "Mode": "Tab",
    "Run": "Enter, J1 B10, X1 Start",
    "L": "Q, J1 B5, X1 LeftShoulder",
    "R": "W, J1 B6, X1 RightShoulder",
    "C-Up": "I, X1 RStickUp",
    "C-Down": "K, X1 RStickDown",
    "C-Left": "J, X1 RStickLeft",
    "C-Right": "L, X1 RStickRight",
    "1": "Z, J1 B3, X1 X",
    "2": "X, J1 B1, X1 A",
    # A WonderSwan is held two ways round: X is the pad you play with, Y the
    # second cross the machine gains when it is turned on its side.
    "X1": "Up, X1 DpadUp",
    "X2": "Right, X1 DpadRight",
    "X3": "Down, X1 DpadDown",
    "X4": "Left, X1 DpadLeft",
    "Y1": "T",
    "Y2": "H",
    "Y3": "G",
    "Y4": "F",
    "Fire": "X, J1 B1, X1 A",
    "Trigger": "X, J1 B1, X1 A",
}

# The analogue axes of the first pad.
DEFAULT_AXES = {
    "X-Axis": {"Value": "X1 LStickX", "Mult": 1.0, "Deadzone": 0.1},
    "Y-Axis": {"Value": "X1 LStickY", "Mult": 1.0, "Deadzone": 0.1},
}


def render_keybinds(machines):
    """Default bindings for every machine's controller."""
    trollers, analog = {}, {}
    for m in machines:
        if not m["loads"]:
            continue
        buttons, axes = declare(m)
        name = f"{m['label']} Controller"

        # Only what a first player touches: a console's own buttons, and the
        # first port's. Anything further along shares keys it should not.
        first_port = port_prefix(m["ports"][0]["name"]) if m["ports"] else None
        bound = {}
        for declared, path in buttons:
            leaf = path.rsplit("/", 1)[-1]
            if leaf not in DEFAULT_KEYS:
                continue
            owner = declared.split(" ")[0]
            if m["ports"] and owner != first_port:
                continue
            bound.setdefault(DEFAULT_KEYS[leaf], declared)
        # setdefault above keeps the FIRST button that wants a key, so a port's
        # second device cannot steal one from the first.
        trollers[name] = {v: k for k, v in bound.items()}

        bound_axes = {}
        for declared, path in axes:
            leaf = path.rsplit("/", 1)[-1]
            if leaf in DEFAULT_AXES and (not m["ports"] or declared.split(" ")[0] == first_port):
                bound_axes.setdefault(leaf, declared)
        if bound_axes:
            analog[name] = {declared: DEFAULT_AXES[leaf] for leaf, declared in bound_axes.items()}

    return {
        "_comment": [
            "GENERATED by waterbox/gen-config.py - do not edit.",
            "Default bindings for the controllers this package declares. The frontend ships none of",
            "its own: a package that declares a controller says how it is played by default, and",
            "Chimera uses that for a controller the user's config has never seen. The user's own",
            "bindings always win, and the controller config's Defaults button comes back here.",
            "Only player one is bound - a second pad is something you plug in deliberately, and the",
            "keys it would take are the ones player one already has.",
        ],
        "AllTrollers": trollers,
        "AllTrollersAutoFire": {},
        "AllTrollersAnalog": analog,
    }


def main():
    check = "--check" in sys.argv
    data = json.load(open(os.path.join(HERE, "machines.json")))
    machines = data["machines"]

    inc = render_inc(machines) + "\n"
    inc_path = os.path.join(HERE, "machines.inc")

    cfg_path = os.path.join(HERE, "waterbox.config")
    cfg = json.load(open(cfg_path))
    cfg["machines"] = render_machines(machines)
    cfg["machineSetting"] = "machine"
    # The buffer has to hold the largest picture any machine draws.
    cfg["video"]["width"] = max(m["maxWidth"] for m in machines if m["loads"])
    cfg["video"]["height"] = max(m["maxHeight"] for m in machines if m["loads"])
    # The machine setting's options are the machines themselves.
    for s in cfg["settings"]:
        if s["name"] == "machine":
            s["options"] = [m["id"].lower() for m in machines if m["loads"]]
    text = json.dumps(cfg, indent=2) + "\n"

    keys_path = os.path.join(HERE, "default_keybinds.json")
    keys = json.dumps(render_keybinds(machines), indent=2) + "\n"

    if check:
        bad = []
        if open(inc_path).read() != inc:
            bad.append("waterbox/machines.inc")
        if open(cfg_path).read() != text:
            bad.append("waterbox/waterbox.config")
        if open(keys_path).read() != keys:
            bad.append("waterbox/default_keybinds.json")
        if bad:
            print("out of date with ares: " + ", ".join(bad), file=sys.stderr)
            print("run ./waterbox/gen-config.py", file=sys.stderr)
            return 1
        print("machines.inc and waterbox.config match what ares says")
        return 0

    open(inc_path, "w").write(inc)
    open(cfg_path, "w").write(text)
    open(keys_path, "w").write(keys)
    total = sum(1 for m in machines if m["loads"])
    print(f"wrote machines.inc, waterbox.config and default_keybinds.json: {total} machines")
    return 0


if __name__ == "__main__":
    sys.exit(main())
