/* GENERATED by waterbox/gen-config.py from waterbox.config - do not edit.
 * The arena the package asks Chimera for, so the gate's runner can ask for
 * the same one and never test a core nobody will run. */
#pragma once

#define ARES_MEMORY_LAYOUT_TEMPLATE { \
	32u << 20, /* sbrk: 32 MiB */ \
	4u << 20, /* sealed: 4 MiB */ \
	16u << 20, /* invisible: 16 MiB */ \
	4u << 20, /* plain: 4 MiB */ \
	2048u << 20, /* mmap: 2048 MiB */ \
}
